SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
spool create_user.log

-- Ensure we are in the correct Pluggable Database (EBSDB)
--ALTER SESSION SET CONTAINER = EBSDB;

-- Drop prexisting user
DROP USER APPS_AI CASCADE;

-- Create the integration user
PROMPT Creating user APPS_AI...
CREATE USER apps_ai IDENTIFIED BY apps_ai default tablespace APPS_TS_TX_DATA quota unlimited on APPS_TS_TX_DATA;

PROMPT Enabling editions
ALTER USER apps_ai ENABLE EDITIONS;

-- Grant basic connectivity
PROMPT Granting connectivity...
GRANT CONNECT TO apps_ai;

-- Grant data access (Adjust this if you prefer specific table grants for security)
PROMPT Granting table access...
GRANT SELECT ANY TABLE TO apps_ai;

-- Create the logon trigger to point to the EBS APPS schema
PROMPT Creating logon trigger...
CREATE OR REPLACE TRIGGER apps_ai.after_logon_trg
AFTER LOGON ON apps_ai.SCHEMA
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = APPS';
END;
/

--grant create procedure to apps_ai;

/* Sequence access used by create_ap_invoice */
GRANT SELECT ON APPS.AP_INVOICES_INTERFACE_S TO apps_ai;
GRANT SELECT ON APPS.AP_INVOICE_LINES_INTERFACE_S TO apps_ai;
GRANT SELECT ON APPS.mtl_material_transactions_s TO apps_ai;


/* DML required by mutating functions in the package */
GRANT INSERT ON APPS.MTL_TRANSACTIONS_INTERFACE TO apps_ai;
GRANT INSERT ON APPS.AP_INVOICES_INTERFACE TO apps_ai;
GRANT INSERT ON APPS.AP_INVOICE_LINES_INTERFACE TO apps_ai;

/* Core EBS package execution */
GRANT EXECUTE ON APPS.FND_GLOBAL TO apps_ai;
GRANT EXECUTE ON APPS.FND_DATE TO apps_ai;
GRANT EXECUTE ON APPS.MO_GLOBAL TO apps_ai;
GRANT EXECUTE ON APPS.FND_API TO apps_ai;
GRANT EXECUTE ON APPS.FND_MSG_PUB TO apps_ai;
GRANT EXECUTE ON APPS.FND_REQUEST TO apps_ai;
GRANT EXECUTE ON APPS.INV_RESERVATION_PUB TO apps_ai;
GRANT EXECUTE ON APPS.INV_RESERVATION_GLOBAL TO apps_ai;
GRANT EXECUTE ON APPS.INV_TXN_MANAGER_PUB TO apps_ai;
GRANT EXECUTE ON APPS.AP_VENDOR_PUB_PKG TO apps_ai;

/* Create log table */
 CREATE TABLE APPS_AI.GGLTOOLBOX$MCP_LOG 
   (	ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE, 
	MCP_CLIENT VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	LOG_LEVEL VARCHAR2(200 BYTE), 
	PROGRAM_UNIT VARCHAR2(100 BYTE), 
	USERNAME VARCHAR2(100 BYTE), 
	LOG_MESSAGE CLOB DEFAULT NULL, 
	CREATED_ON TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(100 BYTE) DEFAULT USER NOT NULL ENABLE
) tablespace APPS_TS_TX_DATA;

/* Create GE SQL Toolkit pl/sql wrapper */
@ge_ebs_mcp_tools.pls
@ge_ebs_mcp_tools.plb

spool off

PROMPT Setup completed successfully.
EXIT;